replicaCount: 2

image:
#  repository: nexus-docker-8082.nexus.svc.cluster.local:8082/my-app
  repository: seongacr.azurecr.io/my-app
  tag: "17"
  pullPolicy: IfNotPresent

# AKS-ACR 연동 시 imagePullSecrets 불필요

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

health:
  path: /health
  port: 8080
